apiVersion: v1
kind: Service
metadata:
  name: matomo-mysql
  labels:
    app: matomo
spec:
  ports:
    - port: 3306
  selector:
    app: matomo
    tier: mysql
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: matomo-mysql
  labels:
    app: matomo
spec:
  selector:
    matchLabels:
      app: matomo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matomo
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
