apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  ports:
    - port: 5000
      name: web
      protocol: TCP
  selector:
    app: docker-registry
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:5000
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /httpasswd_storage/auth
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_STORAGE_S3_ACCESSKEY
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_STORAGE_S3_SECRETKEY
            - name: REGISTRY_STORAGE_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_STORAGE_S3_BUCKET
            - name: REGISTRY_STORAGE_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_STORAGE_S3_REGION
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_STORAGE_S3_REGIONENDPOINT
            - name: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
              valueFrom:
                secretKeyRef:
                  name: storage-config
                  key: REGISTRY_HEALTH_STORAGEDRIVER_ENABLED
          ports:
            - containerPort: 5000
              hostPort: 5000
          volumeMounts:
            - name: htpasswd-secret
              mountPath: /httpasswd_storage
      volumes:
        - name: htpasswd-secret
          secret:
            secretName: basic-auth
