apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: matomodb
  namespace: minsky
  managedFields:
    fieldsType: FieldsV1

spec:
  version: "8.0-v2"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  terminationPolicy: DoNotTerminate