kind: Service
apiVersion: v1
metadata:
  name: drone-server
spec:
  selector:
    app: drone-server
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-server-pv-claim
  labels:
    app: drone-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      name: drone-server
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:1.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
          env:
            - name: DRONE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone-github
                  key: DRONE_GITHUB_CLIENT_ID
            - name: DRONE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-github
                  key: DRONE_GITHUB_CLIENT_SECRET
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-github
                  key: DRONE_RPC_SECRET
            - name: DRONE_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: drone-github
                  key: DRONE_SERVER_HOST
            - name: DRONE_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: drone-github
                  key: DRONE_SERVER_PORT
          volumeMounts:
            - name: drone-server-persistent-storage
              mountPath: /data
      volumes:
        - name: drone-server-persistent-storage
          persistentVolumeClaim:
            claimName: drone-server-pv-claim
      restartPolicy: Always
